"""
JAKECreator: Worker for generating character details based on basic information
"""
from typing import Dict, Any
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser, JsonOutputParser
from pydantic import BaseModel, Field

from src.prompts import PromptManager


class CharacterDetails(BaseModel):
    """Schema for character details"""
    personality: str = Field(description="Character's personality traits")
    character: str = Field(description="Character's distinctive characteristics")
    speaking_style: str = Field(description="Character's way of speaking")
    likes: str = Field(description="Things the character likes")
    dislikes: str = Field(description="Things the character dislikes")
    background: str = Field(description="Character's background story")
    goals: str = Field(description="Character's goals and motivations")


class JAKECreator:
    """
    Worker for generating character details based on basic information given by users
    """

    def __init__(self, model_name: str = "gpt-4o", temperature: float = 0.7):
        """
        Initialize JAKECreator

        Args:
            model_name: OpenAI model to use
            temperature: Temperature for generation (higher = more creative)
        """
        self.llm = ChatOpenAI(model=model_name, temperature=temperature)
        self.prompt_manager = PromptManager()

    def _design_worldview(self, character_basics: Dict[str, Any]) -> str:
        """
        Generate JAKE's worldview based on basic character information

        Args:
            character_basics: Dictionary with basic info (name, age, occupation, etc.)

        Returns:
            str_worldview: String explaining worldview of JAKE
        """
        worldview_prompt = self.prompt_manager.get_worldview_prompt()
        chain = worldview_prompt | self.llm | StrOutputParser()

        worldview = chain.invoke({
            "name": character_basics.get("name", "Unknown"),
            "age": character_basics.get("age", "Unknown"),
            "occupation": character_basics.get("occupation", "Unknown"),
            "additional_info": character_basics.get("additional_info", "None provided")
        })

        return worldview

    def _design_details(
        self,
        str_worldview: str,
        character_basics: Dict[str, Any]
    ) -> Dict[str, str]:
        """
        Generate detailed character traits from worldview

        Args:
            str_worldview: Worldview string generated by _design_worldview
            character_basics: Basic character information

        Returns:
            Dictionary with character details: personality, character, speaking_style,
            likes, dislikes, background, goals
        """
        details_prompt = self.prompt_manager.get_details_prompt()
        chain = details_prompt | self.llm | JsonOutputParser()

        details = chain.invoke({
            "name": character_basics.get("name", "Unknown"),
            "age": character_basics.get("age", "Unknown"),
            "occupation": character_basics.get("occupation", "Unknown"),
            "worldview": str_worldview
        })

        return details

    def create_character(self, character_basics: Dict[str, Any]) -> Dict[str, Any]:
        """
        Complete character creation pipeline

        Args:
            character_basics: Dictionary with basic character info

        Returns:
            Complete character profile including worldview and details
        """
        # Step 1: Design worldview
        worldview = self._design_worldview(character_basics)

        # Step 2: Design detailed character traits
        details = self._design_details(worldview, character_basics)

        # Combine everything
        complete_character = {
            "basics": character_basics,
            "worldview": worldview,
            "details": details,
            "dynamic_profile": ""  # Will be updated during conversations
        }

        return complete_character


# Example usage
if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv()

    creator = JAKECreator()

    character_basics = {
        "name": "Luna",
        "age": "25",
        "occupation": "Cafe owner",
        "additional_info": "Loves books and cozy atmospheres"
    }

    character = creator.create_character(character_basics)

    print("=== Character Created ===")
    print(f"Name: {character['basics']['name']}")
    print(f"\nWorldview:\n{character['worldview']}")
    print(f"\nDetails:\n{character['details']}")
